---
title: Maak een variabele in JavaScript
hero_image: images/banner.png
description: Leer hoe je een variabele in JavaScript kunt maken
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: Inleiding
