---
title: Erstellen Sie eine Variable in JavaScript
hero_image: Bilder / Banner.png
description: Erfahren Sie, wie Sie eine Variable in JavaScript erstellen
theme: rot
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: Schöpfer, Design-0, Programmierung-0, Phys-Comp-0, Herstellung-0, Community-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: Einführung
