---
title: Crea una variabile in JavaScript
hero_image: images / banner.png
description: Scopri come creare una variabile in JavaScript
theme: rosso
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creatore, design-0, programmazione-0, compatta-0, fabbricazione-0, comunità-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: introduzione
