---
title: Opret en variabel i JavaScript
hero_image: images / banner.png
description: Lær, hvordan du opretter en variabel i JavaScript
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skaber, design-0, programmering-0, phys-comp-0, fremstilling-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Introduktion
