---
title: Създайте променлива в JavaScript
hero_image: изображения / banner.png
description: Научете как да създадете променлива в JavaScript
theme: червен
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: създател, дизайн-0, програмиране-0, phys-comp-0, производство-0, общност-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Въведение
