---
title: 创建一个JavaScript变量
hero_image: images/banner.png
description: 学习如何在 JavaScript 中创建变量
theme: 红
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: 创建者, 设计-0, 编程-0, 物理组装-0, 制造-0, 社区-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: 介绍
