---
title: Luo muuttuja JavaScript-muodossa
hero_image: Kuvien / banner.png
description: Opi muokkaamaan JavaScript-muuttuja
theme: punainen #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: luoja, design-0, ohjelmointi-0, phys-comp-0, valmistus-0, yhteisö-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: esittely
