---
title: Creu newidyn yn JavaScript
hero_image: delweddau / banner.png
description: Dysgwch sut i greu newidyn yn JavaScript
theme: Coch
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: crewr, dylunio-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Cyflwyniad
