---
title: Crea una variable en JavaScript
hero_image: images / banner.png
description: Aprenda cómo crear una variable en JavaScript
theme: rojo
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creador, diseño-0, programación-0, phys-comp-0, fabricación-0, comunidad-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: Introducción
