---
title: Creează o variabilă în JavaScript
hero_image: images/banner.png
description: Învață cum să creezi o variabilă în JavaScript
theme: roșu
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programare-0, fiz-comp-0, fabricare-0, comunitate-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Introducere
