---
title: Crie uma variável em JavaScript
hero_image: images / banner.png
description: Aprenda a criar uma variável em JavaScript
theme: vermelho
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: criador, design-0, programação-0, phys-comp-0, manufacture-0, comunidade-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Introdução
