---
title: جاوا اسکرپٹ میں متغیر بنائیں
hero_image: تصاویر / banner.png
description: جاوا اسکرپٹ میں متغیر بنانے کا طریقہ جانیں
theme: سرخ
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: خالق، ڈیزائن 0، پروگرامنگ-0، فیز-کمپ-0، تیاری-0، کمیونٹی-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: تعارف
