---
title: Buat variabel dalam JavaScript
hero_image: gambar / banner.png
description: Pelajari cara membuat variabel dalam JavaScript
theme: merah
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: pencipta, desain-0, pemrograman-0, fisika-comp-0, manufaktur-0, komunitas-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: pengantar
