---
title: Ustvarite spremenljivko v JavaScriptu
hero_image: images / banner.png
description: Več o tem, kako ustvariti spremenljivko v JavaScriptu
theme: rdeča
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: ustvarjalec, design-0, programiranje-0, fiz-comp-0, izdelava-0, skupnost-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: Uvod
