---
title: Hozzon létre egy változót a JavaScript-ben
hero_image: images / banner.png
description: Ismerje meg, hogyan lehet létrehozni egy változót a JavaScript-ben
theme: piros
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: alkotó, design-0, programozás-0, fiz-comp-0, gyártás-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Bevezetés
