---
title: Créer une variable en JavaScript
hero_image: images / banner.png
description: Apprenez à créer une variable en JavaScript
theme: rouge
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: créateur, design-0, programmation-0, phys-comp-0, fabrication-0, communauté-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: introduction
