---
title: Create a variable in JavaScript
hero_image: images/banner.png
description: Learn how to create a variable in JavaScript
theme: rojo
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Robot parlanchín
