---
title: Utwórz zmienną w JavaScript
hero_image: images / banner.png
description: Dowiedz się, jak utworzyć zmienną w JavaScript
theme: czerwony
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: twórca, design-0, programowanie-0, phys-comp-0, production-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Wprowadzenie
