---
title: Vytvorte premennú v jazyku JavaScript
hero_image: images / banner.png
description: Zistite, ako vytvoriť premennú v jazyku JavaScript
theme: červená
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tvorca, dizajn-0, programovanie-0, phys-comp-0, výroba-0, komunita-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: úvod
