---
title: Hada abun yi a javascript
hero_image: hotuna/banner
description: Koya yanda ake hada abu indan akayi amfani da Javascript
theme: ja
duration: 0
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Gaisuwa
