---
title: Buat pemboleh ubah dalam JavaScript
hero_image: imej / banner.png
description: Ketahui cara membuat pemboleh ubah dalam JavaScript
theme: merah
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: pencipta, reka bentuk-0, pengaturcaraan-0, phys-comp-0, pembuatan-0, komuniti-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Pengenalan
