---
title: Buat pemboleh ubah dalam JavaScript
hero_image: imej / banner.png
description: Ketahui cara membuat pemboleh ubah dalam JavaScript
theme: merah #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: pencipta, reka bentuk-0, pengaturcaraan-0, phys-comp-0, pembuatan-0, komuniti-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Pengenalan
