---
title: Δημιουργήστε μια μεταβλητή στο JavaScript
hero_image: εικόνες / banner.png
description: Μάθετε πώς μπορείτε να δημιουργήσετε μια μεταβλητή στο JavaScript
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: δημιουργός, σχεδιασμός-0, προγραμματισμός-0, phys-comp-0, κατασκευή-0, κοινότητα-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Εισαγωγή
