---
title: Javascript හි කාර්යයක්(function එකක්) නිර්මාණය කිරීම 
hero_image: images / banner.png
description: JavaScrit මගින් කාර්යයක්(function එකක්) නිර්මාණය කරන්නේ කෙසේදැයි ඉගෙන ගැනීම
theme: රතු
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: නිර්මාණකරු, සැලසුම්-0, කේතන වැඩසටහන්-0, භෞතික-පරිගනක-0, නිෂ්පාදනය-0, ප්‍රජා-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: හැදින්වීම
