---
title: JavaScript'te bir değişken oluşturun
hero_image: images / banner.png
description: JavaScript'te bir değişken oluşturmayı öğrenin
theme: kırmızı
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programlama-0, fiz-comp-0, production-0, topluluk-0
interests: ""
technologies: ""
site_areas: ""
steps:
  - 
    title: Giriş
